apiVersion: 1

datasources:
  - name: Metrics
    uid: vm
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    jsonData:
      httpMethod: GET
      timeInterval: 15s

  - name: Logs
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Traces
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
      serviceMap:
        datasourceUid: vm
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
