# Define default networks for all services
x-networks: &default-networks
  networks:
    - karakeep
    - cloudflare_tunnel

services:
  web:
    <<: *default-networks
    container_name: karakeep
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - /mnt/tank/container-configs/karakeep:/data
    ports:
      - 4000:3000
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      NODE_OPTIONS: --dns-result-order=ipv4first
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      CRAWLER_NUM_WORKERS: ${CRAWLER_NUM_WORKERS}
      DISABLE_SIGNUPS: ${DISABLE_SIGNUPS}
      CRAWLER_FULL_PAGE_ARCHIVE: ${CRAWLER_FULL_PAGE_ARCHIVE}
      CRAWLER_VIDEO_DOWNLOAD: ${CRAWLER_VIDEO_DOWNLOAD}
      CRAWLER_VIDEO_DOWNLOAD_MAX_SIZE: ${CRAWLER_VIDEO_DOWNLOAD_MAX_SIZE}
      CRAWLER_VIDEO_DOWNLOAD_TIMEOUT_SEC: ${CRAWLER_VIDEO_DOWNLOAD_TIMEOUT_SEC}
      INFERENCE_NUM_WORKERS: ${INFERENCE_NUM_WORKERS}
      INFERENCE_CONTEXT_LENGTH: ${INFERENCE_CONTEXT_LENGTH}
      CRAWLER_STORE_PDF: ${CRAWLER_STORE_PDF}

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS

  chrome:
    image: ghcr.io/karakeep-app/karakeep-chrome:release
    restart: unless-stopped
    init: true
    container_name: chrome
    networks:
      - karakeep
    command:
      - --disable-gpu
      - --disable-dev-shm-usage
      - --hide-scrollbars
      - --disable-blink-features=AutomationControlled
      - --window-size=1440,900
    ports:
     - 9222:9222
  meilisearch:
    <<: *default-networks
    container_name: mellisearch
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /mnt/tank/container-configs/melisearch:/meili_data

volumes:
  data:

networks:
  karakeep:
  cloudflare_tunnel:
    external: true