x-networks: &default-networks
  networks:
    - glance
    - cloudflare_tunnel


services:
  git-sync:
    # <<: *default-networks
    container_name: git-sync
    image: registry.k8s.io/git-sync/git-sync:v4.4.2
    restart: unless-stopped
    command: [
      "git-sync",
      "--repo=https://github.com/mspiegel31/home-services.git",
      "--ref=main",
      "--root=/git",
      "--link=current",
      "--period=2s",
      "--username=mspiegel31",
      "--add-user",
      # exposes git-sync readiness after the first successful sync
      "--http-bind=:1234",
      ]
    environment:
      - GITSYNC_PASSWORD=${GITSYNC_PASSWORD}
    volumes:
      - /opt/glance-configs:/git
    user: "1000:1000"
    healthcheck:
      test: ["CMD-SHELL", "test -f /git/current/services/glance/config/glance.yml && curl -f http://localhost:1234/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  glance:
    <<: *default-networks
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    entrypoint: ["/app/glance", "--config", "/git/current/services/glance/config/glance.yml"]
    volumes:
      - /opt/glance-configs:/git:ro
      # Optionally, also mount docker socket if you want to use the docker containers widget
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - AWS_SSO_URL=${AWS_SSO_URL}
      - INFRA_DOCS_URL=${INFRA_DOCS_URL}
      - GRAFANA_URL=${GRAFANA_URL}
      - SPACELIFT_URL=${SPACELIFT_URL}
      - CODEFRESH_URL=${CODEFRESH_URL}
      - WIZ_URL=${WIZ_URL}
    depends_on:
      git-sync:
        condition: service_healthy

networks:
  glance:
  cloudflare_tunnel:
    external: true
