name: Deploy Stacks

on:
  push:
    paths:
      - 'services/**'
      - '.github/portainer-webhooks.yml'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Trigger Portainer webhooks
        uses: ./.github/actions/portainer-webhook
        with:
          base-url: ${{ secrets.PORTAINER_BASE_URL }}
          cf-access-client-id: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          cf-access-client-secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
